FROM node:20-slim
WORKDIR /app
COPY package.json package-lock.json* ./
RUN --mount=type=cache,id=s/d4d8803d-ff57-46be-8331-90fe412a1ec5-/root/npm,target=/root/.npm npm install
COPY . .
ENV NODE_ENV=production
ENV PORT=8000
EXPOSE 8000
CMD ["npm","start"]
